# Generated by Django 4.2.20 on 2025-03-29 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_paciente', models.CharField(max_length=255)),
                ('edad', models.CharField(max_length=10)),
                ('identificacion', models.CharField(max_length=50, unique=True)),
                ('procedencia', models.CharField(max_length=255)),
                ('ocupacion', models.CharField(max_length=255)),
                ('acompanante', models.CharField(blank=True, max_length=255, null=True)),
                ('motivo_consulta', models.TextField()),
            ],
        ),
    ]
