# Generated by Django 5.1.7 on 2025-04-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('nombre_paciente', models.CharField(max_length=255)),
                ('edad', models.CharField(max_length=10)),
                ('identificacion', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('procedencia', models.CharField(max_length=255)),
                ('ocupacion', models.CharField(max_length=255)),
                ('acompanante', models.CharField(blank=True, max_length=255, null=True)),
                ('motivo_consulta', models.TextField()),
                ('enfermedad_actual', models.CharField(blank=True, max_length=255, null=True)),
                ('antecedentes_patologicos', models.TextField(blank=True, null=True)),
                ('antecedentes_farmacologicos', models.TextField(blank=True, null=True)),
                ('antecedentes_alergicos', models.TextField(blank=True, null=True)),
                ('plan_de_manejo', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
