# Generated by Django 5.1.7 on 2025-03-30 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historias_clinicas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historiaclinica',
            name='id',
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='identificacion',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
